### PR TITLE
Fixed zarray assignments

### LINKED ISSUE #13: zarray assignment errors
Assigning an `xarray` to a `zarray` doesn't seem to work:
```cpp
auto a1 = xarray<int>();
auto a2 = xarray<int>({0, 1});
zarray z1(a1);
z1 = a2;
```
```
/home/david/miniforge3/envs/xtensor-zarr-dev/include/zarray/zarray_impl.hpp:462:9: error: no matching function for call to 'xt::xarray_container<xt::uvector<int, std::allocator<int> >, (xt::layout_type)1, xt::svector<long unsigned int, 4, std::allocator<long unsigned int>, true>, xt::xtensor_expression_tag>::resize(const shape_type&) const'
         m_array.resize(shape);
         ^~~~~~~
```
With `noalias` either:
```cpp
auto a1 = xarray<int>();
auto a2 = xarray<int>({0, 1});
zarray z1(a1);
noalias(z1) = a2;
```
```
/home/david/miniforge3/envs/xtensor-zarr-dev/include/zarray/zassign.hpp:32:17: error: 'const class xt::xarray_container<xt::uvector<int, std::allocator<int> >, (xt::layout_type)1, xt::svector<long unsigned int, 4, std::allocator<long unsigned int>, true>, xt::xtensor_expression_tag>' has no member named 'assign_to'; did you mean 'assign'?
             rhs.assign_to(lhs.get_implementation());
             ~~~~^~~~~~~~~
             assign
```
Wrapping `a2` in a `zarray` and assigning it fails at run-time:
```cpp
auto a1 = xarray<int>();
auto a2 = xarray<int>({0, 1});
zarray z1(a1);
zarray z2(a2);
z1 = z2;
```
```
unknown file: Failure
C++ exception with description "callback not found" thrown in the test body.
```

### PR DESCRIPTION
**Pull request by davidbrochart**
Fixes #13

### CODE REVIEW

**Comment by davidbrochart** [comment]
Trigger CI

**Comment by davidbrochart** [comment]
Trigger CI

File: include/zarray/zassign.hpp [hunk 1]
```diff
@@ -15,6 +15,32 @@
...
+
+        template <>
+        struct zexpression_assigner<xtensor_expression_tag>
+        {
+            // E1 is a zarray_expression, E2 is an xtensor_expression
+            template <class E1, class E2>
+            static void assign_data(E1& e1, const E2& e2)
+            {
+                using value_type = typename E2::value_type;
+                e1.template get_array<value_type>() = e2;
```
Comment (davidbrochart) [inline include/zarray/zassign.hpp:39]: What if the array wrapped by `e1` is not of type `E2::value_type`?

Comment (JohanMabille) [reply include/zarray/zassign.hpp:39]: I'm afraid it won't work

Comment (davidbrochart) [reply include/zarray/zassign.hpp:39]: What should be the desired behavior? Should it cast the source type to the destination type, or create a new array with the source data type?

Comment (JohanMabille) [reply include/zarray/zassign.hpp:39]: Actually I wonder if the assign operator should not xwrap the xtensor expression in a temporary zarray before dispatching the assignment. But this would not work with `noalias`.

Creating a new array with the correct `value_type` could be a solution, but that would be dangerous because you may accidentally erase an array when you want to read while it is not const:

```cpp
xt::xarray<double> a;
zarray<double> za(a);
auto c = za.get_array<int>(); // Dangerous: za now wraps an empty array of int.
std::cout << c(0, 0) << std::endl;
```
